name: CI/CD for Frontend

on:
  push:
    branches:
      - main  # Change this to your main branch name (e.g., "master" if you are using the "master" branch)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test

    - name: Build app
      run: npm run build

    - name: Deploy to S3 bucket
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --delete

